### PR TITLE
Add the two missing delegate properties

### PR DESCRIPTION
**Pull request by orta**
Looks like the additions of some new protocol didn't get corresponding  properties, so if you were using any of the APIs further down the indexes were not congruent with `JSApplicationDelegateSubprotocols`.

### CODE REVIEW

**Comment by JaviSoto** [comment]
Ooops nice catch!!

**Comment by robinsenior** [comment]
Ah, thanks for spotting that @orta, my mistake

**Comment by robinsenior** [comment]
@JaviSoto will you be doing a new cocoapods release for the iOS 9 features?

**Comment by JaviSoto** [comment]
Yes, let me get on to that.

**Comment by JaviSoto** [comment]
The podspec fails to validate, all I see are these warnings:

```
-> JSDecoupledAppDelegate (1.2.0)
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:36:27: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:106:145: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:106:187: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:106:226: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:113:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:113:99: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:116:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:116:87: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:116:142: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:116:181: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:120:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:120:151: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:120:197: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:120:236: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:128:21: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:128:50: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:128:117: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:128:155: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:129:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:129:86: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:130:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:130:89: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:131:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:131:94: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:132:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:132:93: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:138:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:138:65: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:138:99: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:138:131: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:140:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:140:57: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:140:100: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:148:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:148:106: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:148:145: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:156:68: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:164:70: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:165:67: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:172:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:172:95: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:172:134: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:172:118: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:179:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:179:96: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:186:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:186:93: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:187:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:187:87: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:187:138: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:187:127: warning: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:188:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:188:98: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:188:132: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:189:36: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  |  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.h:189:88: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    - WARN  | [iOS]  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.m:207:1: warning: conflicting return type in implementation of 'application:supportedInterfaceOrientationsForWindow:': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned int') [-Wmismatched-return-types]
    - NOTE  |  /Applications/Xcode7.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:336:1: note: previous definition is here
    - WARN  | [iOS]  JSDecoupledAppDelegate/JSDecoupledAppDelegate/JSDecoupledAppDelegate.m:207:1: warning: conflicting return type in implementation of 'application:supportedInterfaceOrientationsForWindow:': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long') [-Wmismatched-return-types]

[!] The podspec does not validate.
```

Are those the reason why it doesn't validate?
I can fix those issues on the header, but not until later today.

**Comment by robinsenior** [comment]
Ugh, yeah, if you add one nullability qualifier, you need to add them all. Are there any issues adding the qualifiers for people who aren't on Xcode 7?

**Comment by JaviSoto** [comment]
Yeah, it breaks their build lol. I can add them conditionally though. I'll try to do this later.

**Comment by orta** [comment]
you can use `--ignore warnings` to ignore the warnings from Xcode and ship the pod anyway, which in this case makes sense, though supporting XC7+ is probably reasonable, given how the library works and why anyone would update.

**Comment by robinsenior** [comment]
it also looks like there are some duplicate `#endif`s in there, probably copypasta or a bad merge. If you're fixing the nullability qualifiers you can clean those up too.

**Comment by JaviSoto** [comment]
I'm working on this now.

Which are duplicate?

**Comment by JaviSoto** [comment]
I fixed all the warnings, but pod trunk push seems to be checking an older version for some reason...
I'll use --ignore-warnings.

**Comment by JaviSoto** [comment]
OK It's pushed as 1.2.0 with these changes: https://github.com/JaviSoto/JSDecoupledAppDelegate/commit/8489a4c74e04d03a3f01cc02201d3a3936777a86 :)

**Pull request merged**
